# Generated by Django 5.1 on 2025-04-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventin", "0002_inscricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscricao",
            old_name="deta_incricao",
            new_name="data_inscricao",
        ),
    ]
